/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ll;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class App {
    public static void main(String[] args) {
        String url = "jdbc:mysql://localhost:3306/simpleDb_test";
        String username = "root";
        String password = "1234";

        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;

        try {
            // 1. 드라이버 클래스 로드
            Class.forName("com.mysql.cj.jdbc.Driver");

            // 2. 데이터베이스 연결
            connection = DriverManager.getConnection(url, username, password);

//            // 3. 쿼리 실행
            statement = connection.createStatement();
            if (statement == null) {
                System.out.println("연결 실패");
            }else {
                System.out.println("연결 성공");
            }
//            resultSet = statement.executeQuery("SELECT * FROM yourTable");
//
//            // 4. 결과 출력
//            while (resultSet.next()) {
//                int id = resultSet.getInt("id");
//                String name = resultSet.getString("name");
//                System.out.println("ID: " + id + ", Name: " + name);
//            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (connection != null) connection.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
